### ISSUE TITLE
Tasks: UI Polish

### ISSUE THREAD

**Issue by maxbrunsfeld** [zed-industries/zed#10132]
### Check for existing issues

- [X] Completed

### Describe the feature

Some minor changes that we came up with to make the Tasks feature more polished and discoverable:

* [ ] @osiewicz adds task discoverability improvements
* [x] bug: with default settings, after running a task, nothing is focused.
    * By default, focus should not change - restore the previous focus on closing the task modal
* [x] Add a "play" icon in the status bar that, when clicked, opens the task modal
    * This icon could have a status indicator
        * red if any open task tab failed
        * else, yellow if any open task tab is still running
        * else, green if there tasks tabs open, and they have all succeeded
        * else, no indicator if there are no open task tabs
* [x] change the placeholder text of the task modal
    * lets de-emphasize "task name as prompt" / oneshot use case
    * Maybe just "Run a task..."
* [x] Remove 'language extension' secondary text, instead display an icon indicating the language extension
    * new trait method on the `TaskSource`
* [x] Task tabs for "run current function" should just say: "Rust: test_foo_bar", to make it easy to scan which test is running
    * use this same name in the task modal
    * same thing for "Test current crate", "cargo check current crate"

**Comment by jansol** [comment]
Related:  #9633

**Comment by JustFrederik** [comment]
Indicators right next to the code would be great
<img width="160" alt="Screenshot 2024-04-16 at 17 23 05" src="https://github.com/zed-industries/zed/assets/121750393/a759bb3f-89a1-4bc5-ae77-aa54ff38fdaa">
<img width="145" alt="Screenshot 2024-04-16 at 17 22 56" src="https://github.com/zed-industries/zed/assets/121750393/0514a819-3acd-4315-ad60-589393fe5ca5">
<img width="144" alt="Screenshot 2024-04-16 at 17 22 22" src="https://github.com/zed-industries/zed/assets/121750393/434d120f-d769-4391-84af-f180bbd4a88c">

**Comment by SomeoneToIgnore** [comment]
The remaining open task is being done in https://github.com/zed-industries/zed/pull/11195 so closing this optimistically.
