### ISSUE TITLE
Linux Preview Tracking issue

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/zed#12403]
### High level goals: 

- [x] X11 performance
- [ ] Add Client Side Decorations for:
  - [ ] resizing https://github.com/zed-industries/zed/issues/11469  https://github.com/zed-industries/zed/issues/10976 
  - [x] moving
  - [ ] Drop shadow
- [x] Render a menu @iamnbutler https://zed.dev/channel/linux-1201/notes#Linux-Menus
- [x]  improve GPUI prompts @iamnbutler  (https://github.com/zed-industries/zed/issues/9810 https://github.com/zed-industries/zed/issues/9203) 
- [x] Remove non-functional mic and screenshare UI
- [x] Augment 'copy system specs' with Linux related info
- [x] Make blade errors more helpful 
- [ ] Bundle `git` binaries in archive
- [x] Rename Zed binaries one last time https://github.com/zed-industries/zed/issues/12290, https://github.com/zed-industries/zed/issues/12306
- [x] Support XDG trash
- [x] Resolve all `todo(linux)`
- [x] Fix scrolling
- [x] Decide how to distribute the binary
- [x] Fix modifiers getting stuck on
- [x] Fix seg fault on exit
- [x] Fix the cursor sometimes not changing

### Bad Bugs:

- [ ] Code actions not working strangely
- [x] Fix weird linux freezing - https://github.com/zed-industries/zed/issues/12339
- [ ] Fix ’thread 'async-io' panicked at 'local task dropped by a thread that didn't spawn it'
- [x] Drag and drop + Clipboard issue on GNOME (prior art: https://github.com/apricotbucket28/zed/tree/wayland-own-clipboard) https://github.com/zed-industries/zed/issues/12054
- [x] Ship Alacritty update: https://github.com/zed-industries/zed/issues/12114
- [x] X11:  Bad rendering issue somewhere: https://github.com/zed-industries/zed/issues/11236
- [x] Make sure auto updating is working: https://github.com/zed-industries/zed/issues/11114
- [ ] Double check that quitting is working: https://github.com/zed-industries/zed/issues/11093 
- [x] Fix tests https://github.com/zed-industries/zed/issues/10382 https://github.com/zed-industries/zed/issues/10427 
- [x] Clean up log file https://github.com/zed-industries/zed/issues/10246
- [x] Double check scrolling feel https://github.com/zed-industries/zed/issues/10081 
- [x] X11: crash after unmaximizing window https://github.com/zed-industries/zed/issues/9252 
- [x] X11: "Input event handling"? https://github.com/zed-industries/zed/issues/8931 
- [x] Alt getting stuck on
- [x] Resizing pointer style not showing up
- [ ] Lines are rendered too wide and look wrong: https://github.com/zed-industries/zed/issues/12599

#### Terminal

- [ ] No context menu in the terminal element on right click
- [ ] No way to do "cmd-a, cmd-c" to copy all text, as on mac
- [x] cmd-w is a default to close tabs now, but it is also an emacs "cut the word" keybinding - closing a tab instead of deleting a word is very annoying
- [ ] No way to search in the terminal element (cmd-f on mac) 
- [ ] ctrl-e opens a tab picker instead of emacs "go to end of the line" keybinding

### Maybe stretch goal
- [x] Copy / paste has wrong binding: https://github.com/zed-industries/zed/issues/11912
- [x] Tasks might not look right https://github.com/zed-industries/zed/issues/11481

### Stretch goals

- [ ] Fix blade bleeding https://github.com/zed-industries/zed/issues/12352 https://github.com/zed-industries/zed/issues/11056
- [x] Duplicate keystrokes when changing seats: https://github.com/zed-industries/zed/issues/11966
- [ ] Too many open files: https://github.com/zed-industries/zed/issues/10310
- [ ] Headless mode requires a lot of GUI related libraries
- [x] “Could not start watcher on parent directory” https://github.com/zed-industries/zed/issues/12297 https://github.com/zed-industries/zed/issues/11345 
- [ ] The text system. That's it. That's the issue. There's a lot of TODOs in there, and lots of issues: https://github.com/zed-industries/zed/issues/11703 https://github.com/zed-industries/zed/issues/12176 https://github.com/zed-industries/zed/issues/11323  https://github.com/zed-industries/zed/issues/10890 
- [ ] Decide how to handle XDG issues: https://github.com/zed-industries/zed/issues/11089
- [x] Activate linux tests
- [x] Other TODOs in Linux

### Thorsten's Bug Collection (needs to be confirmed & prioritized)

- [x] X11: creating new buffer and saving file opens wrong project folder in file picker
- [x] Are `settings.json` being watched for changes on Linux?

**Comment by mikayla-maki** [comment]
### ✅ TODOs that should be resolved https://github.com/zed-industries/zed/pull/12514


- [x] Remove clippy allows in platform linux
- [x] GPUI APIs:
    - [x] activate()
    - [x] hide()
    - [x] unhide_other_apps() (probably macOS exclusive)
   - [x] active_window()
   - [x] path_for_auxiliary_executable() (probably macOS exclusive)
   - [x] display() (and related APIs)
   - [x] mouse_position()
   - [x] modifiers()
   - [x] is_active()
   - [x] set_edited() (probably macOS exclusive)
   - [x] show_character_palette (probably macOS exclusive)
