### ISSUE TITLE
Tracking Issue for Zed REPL

### ISSUE THREAD

**Issue by rgbkrk** [zed-industries/zed#13942]
Building on #12062, #9778, #5273 and other issues labeled https://github.com/zed-industries/zed/labels/jupyter, this is a tracking issue for inline code running in Zed.

### Media

* [x] Blog post announcement (@rgbkrk)
  * "Hitting preview this week!", basic workflows, background
* [x] Prep videos and GIFs

### Settings

* [x] Flip `jupyter.enabled` to default to true, allow people to turn it off

### Architecture Polish

- [x] Delete outputs from editor when surrounding lines deleted (Done in #14116)
- [x] Switch from a global Panel to a `View` for managing the runtimes
  - Rip out the panel, switch to tabbed content for kernel logs and debug info (available kernels) @maxdeviant  
- [x]  Support `# %%` format for code cells/blocks (see https://jupytext.readthedocs.io/en/latest/formats-scripts.html)

### Keybindings

- [x] On all platforms, switch to the following keybindings:

* `ctrl-shift-enter` - runs the current block (cell/line/selection) and moves down to next block
* `ctrl-alt(option)-enter` - runs the current block

### Kernel Support

- [x] Ark R kernel issue related to kernel_info_request on start: https://github.com/posit-dev/positron/issues/3864
- [x] Jupyter kernel blocking on shell reply #14146 
- [x] Check the running kernel's `process.status()` #14782

### Output Polish

- [x] Table output using `application/vnd.dataresource+json` needs to be able to show larger tables (Done in #14026)
- [x] Show spinner when executing and queued
- [x] Use the `Muted` styling for the `Executing...` and `Queued` text (Done in #14529)
- [x] Show a close button to clear out an output, on the right hand side of the output.
- [x] Newline issue at the end of the buffer
  - If there's already a newline at the end of the buffer, avoid inserting a new one

### Kernel Discovery

- [x] Improve the kernel discovery process to handle various installation methods (system, virtualenv, poetry, etc.).
- [x] Create a way to refresh the available kernels on demand
- [x] Detect conda environments and active python environments

### Documentation:

- [x] Update documentation to explain how users can configure kernels for their projects.
- [x] Provide examples of .zed/settings.json configurations for kernel selection.

### Stretch goals

If we can make it in time,

* Emit `text/plain` media type within assistant panel when repl used there, to allow model to iterate with you
* Improve the kernel discovery process to handle various installation methods (system, virtualenv, poetry, conda, etc.). Partially done in https://github.com/zed-industries/zed/pull/15047
* Clicking on the last line before a block decoration makes the cursor disappear

**Comment by rgbkrk** [comment]
Shipped!
