### ISSUE TITLE
Remote Development

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/zed#18931]
- [x] Have a remote server build of Zed
- [x] Create an SSH connection between this remote server and Zed
- [x] Use the existing collab protocol to implement remote development
- [x] Get LSP servers running on the remote host
- [x] Improve settings on remote servers
  - [x] [@mikayla-maki] Load ~/.zed/settings.json on remote host, stop sending local user settings to remote host
  - [x] `open settings` should not add worktrees to your remote project
  - [x] Add `open host settings` command that opens `~/.zed/settings.json` on the remote host
        maybe rename "open local settings" to "open project settings"
  - *Important use case* supplying paths to language servers in `lsp` setting
- [ ] Improve visibility into errors when setting up LSPs
- [ ] Meta tasks:
  - [ ] [@osiewicz] Disable and remove dev servers
    - [ ] unable to delete dev server: https://github.com/zed-industries/zed/issues/18884#issuecomment-2402043990
  - [x] [@mrnugget] Docs
  - [ ] [@notpeter] Git story
  - [x] [@mrnugget @bennetbo] Reliability:
    - [x] Logs from remote
    - [x] Panic handler on remote
    - [x] LSP logs
- [x] [@mrnugget @bennetbo] Disconnect handling
  - [x] Investigate hang when reconnecting on timeout
  - [x] Show a "disconnected" overlay when connection is lost
    - only show it after 3 reconnect attempts fail
- [x] [@mrnugget @bennetbo] Workspace persistence/Worktrees/Project Paths
  - [x] [@mrnugget @bennetbo] Cannot open absolute paths in history, because they assume the paths are local
  - [x] [@mrnugget @bennetbo] ssh host always retains worktrees (even if you remove them / all buffers are closed)
- [x] [@mikayla-maki] Allow LSPs to auto-resolve
- [x] [@osiewicz @danilo-leal] Improve UI keyboard navigation

Remote Dev follow up:
- [ ] Adjust extension API to allow remote extensions
- [ ] Use remote-local ollama with AI assistant
- [ ] Per-session port forwarding
- [ ] Improve management of remote-server binaries
  - [ ] Update the remote server binaries eagerly after auto-updating Zed
  - [ ] Delete old remote server binaries after updating
  - [ ] Add configuration where you download auto update from
  - [ ] Do not always fetch the newest version
