### ISSUE TITLE
Markdown improvements

### ISSUE THREAD

**Issue by nathansobo** [zed-industries/zed#5346]
[All Markdown issues](https://github.com/zed-industries/community/issues?q=is%3Aopen+is%3Aissue+label%3Amarkdown+sort%3Areactions-%2B1-desc)

## LSP

Investigate this, this may solve multiple other requests

- [ ] https://github.com/zed-industries/zed/issues/5243

## Syntax highlighting

- [ ] https://github.com/zed-industries/zed/issues/5217
- [ ] [`_` breaks highlighting](https://github.com/zed-industries/zed/issues/5346)
- [ ] https://github.com/zed-industries/community/issues/125
- [x] https://github.com/zed-industries/community/issues/604

## Render / Embed

- [ ] Render bold text bold, italic text italic, etc.
- [ ] Image embed
- [ ] Document embedding via multibuffers ([@Kethku's suggestion](https://github.com/zed-industries/zed/issues/1679#issuecomment-1265733773))
- [ ] https://github.com/zed-industries/zed/issues/5313
- [ ] [Cmd+click to open external hyperlinks](https://github.com/zed-industries/zed/issues/992)
- [ ] https://github.com/zed-industries/zed/issues/5087

## Autocomplete / Autoformatting

- [ ] https://github.com/zed-industries/zed/issues/5089
- [ ] https://github.com/zed-industries/community/issues/23
- [ ] https://github.com/zed-industries/zed/issues/5226

## Misc

- [ ] https://github.com/zed-industries/zed/issues/5305

**Comment by bbkane** [comment]
Inline image rendering would make a HUGE impact on how I write Markdown (it's currently the main reason I use https://typora.io/ ) (see [my blog](https://www.bbkane.com/blog/how-i-take-notes/) for more ~~ranting~~ information about what I need to take notes)

**Comment by red-co** [comment]
Can we add support for id anchor jumps in Markdown, // If possible, allow this specific syntax to jump directly into the editor in any source code comment block.     
    
The problem with line jumps is that the number of lines can be easily changed. The  problem with header jumps is that it needs to be as specific as possible as a header, preferably a sentence, not a few words. But when you want to reference it, set a link, jump to a location, you want it to be no  longer than 8 characters.     

Some editors allow setting ids or aliases for headers.    
    
It may be implemented with html like `<a id="anchor">name</a>`, but this hack only works for page html, and editor inside  jumps do not support it.
