### ISSUE TITLE
Workspace serialization additions

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5869]
### Check for existing issues

- [X] Completed

### Describe the feature

- [ ] zed-industries/zed#5058
- [ ] zed-industries/zed#5258 
- [ ] zed-industries/zed#4985
- [ ] zed-industries/zed#4942
- [ ] zed-industries/zed#4910
- [ ] zed-industries/zed#4683
