### ISSUE TITLE
Add other keymaps

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5903]
Keymap creation should be prioritized in this order.
- [x] zed-industries/feedback#906
- [x] zed-industries/feedback#907
- [ ] zed-industries/feedback#903
- [x] zed-industries/feedback#902

Atom is first, since it was recently shelved, and VS Code is last, because our default bindings are nearly identical to VS Code already.

Any others we should consider?

**Note**: contributors do not need to follow the order suggested above, this is simply the order I'll be following as I work on these.
