### ISSUE TITLE
Clicking "restart to update" should save your changes before restarting

### ISSUE THREAD

**Issue by leifu1128** [zed-industries/zed#7237]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Self explanatory, seems like an oversight. 

### Environment

Zed: v0.121.1 (Zed Preview)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Here are all of the issues tracking what that looks like. Going to close this one out in favor of upvotes on these.

- [ ] zed-industries/zed#5058
- [ ] zed-industries/zed#5258 
- [ ] zed-industries/zed#4985
- [ ] zed-industries/zed#4942
- [ ] zed-industries/zed#4683
