### ISSUE TITLE
Tracking Issue: git integration

### ISSUE THREAD

**Issue by mrnugget** [zed-industries/zed#8665]
## Problem

Our current git integration is very minimal. What we have:

- showing current branch, selecting branches
- showing git status in gutter, until changes are staged
- showing git status in project panel
- navigating to previous/next hunk

Many users are asking for more git integration:

- A "git panel" similar to the VS Code one: https://github.com/zed-industries/zed/issues/4367
- A diff view for things that changed: https://github.com/zed-industries/zed/issues/4523
- Ability to interact with git status gutter and undo changes: https://github.com/zed-industries/zed/issues/4630

## Goal

Build a 0.1 of git integration that fixes immediate pain points and stops users from leaving Zed to go to GitHub, GitLab, or another editor to use a git feature.

The most common git interactions should be doable inside Zed: committing, staging, unstaging, viewing diffs, ...

They should allow keyboard-only workflow.

## Current status

Work on `git integration` is paused at the moment, since we're spread too thin on a lot of other projects.

## Roadmap

Ranking here very subjective and based on personal pain points.

### Milestone 1 - `git blame`

* [x] `git blame` in gutter, toggle on off - https://github.com/zed-industries/zed/pull/8889
* [x] `git blame` inline in the editor - https://github.com/zed-industries/zed/pull/10398
* [x] More information in git blame tooltips
  * [x] Links to PR: https://github.com/zed-industries/zed/pull/10784
  * [x] Avatars: https://github.com/zed-industries/zed/pull/10767
  
### Milestone 2 - `git diff`

* Support diffs
  - Allow opening diffs from git status view

### Milestone 3 - `git status` & `git commit`

* git status view
  - see: working directory is clean or dirty
  - see: untracked, unstaged, staged files
  - do: stage/unstage files
* `git commit` 
  - triggered from git status view
  - opens git commit message
  
### Things we have to do

* Support opening sub-folders (or single files) of git repositories

### Milestone ...

* History (see: https://github.com/zed-industries/zed/issues/10807)
* ...

**Comment by Moshyfawn** [comment]
I think #8663 can be added here.

**Comment by d1y** [comment]
I am really looking forward to using most of the [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) features in zed:  #6780

**Comment by Jaskerv** [comment]
Can I add a feature request for a option to have `file changed` in a tree view? 🙏

**Comment by justAdevTV** [comment]
I want git blame

**Comment by uroybd** [comment]
Conventional commit support in `git commit` will be great.

Alternatively, we can allow plugins to take care of these things like this one: https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits

**Comment by taunusflieger** [comment]
Would be nice if you work in a folder below the git root and get ask if you want to locate the repo (as it is done in vscode). Currently if you are not opening the git root, but a sub directory git support is not enabled.

**Comment by sosickstudio** [comment]
Just wanted to drop in there that the new git integration should allow for multiple git's inside an open folder, I like to be able to have my container open so I can work on multiple services at the same time.

**Comment by Ph0enixKM** [comment]
We could also have some form of Merge Editor like it is in Visual Studio Code or maybe something even better

**Comment by fhamm** [comment]
It would also be great if the proposed source control view is compatible with git submodules, similar to VS Code =)

**Comment by Moshyfawn** [comment]
@mrnugget you might want to link to #10807 where you mention the history milestone.

**Comment by mrnugget** [comment]
Update here: we're going to pause work on the git integration for a few weeks, since we have a lot of projects going on right now — Tasks, Linux, remoting, AI — and are spread a bit too thin. Since we've reached a good pause-point here (just checked off Milestone 1), we'll pause work on git, focus on other projects for a while and then come back to git integration once we've finished other projects or reached significant milestones.

**Comment by SomeoneToIgnore** [comment]
To soften the wait slightly, I hope to finish and merge https://github.com/zed-industries/zed/pull/11080 that enabled git hunk diffs browsing in the editor.
It's not a full diff view, but something useful still.

**Comment by indrajit-roy-sc** [comment]
Can the community chip in on this? Would love to see the approach and design hosted somewhere so that folks who want to contribute are able to raise PRs and help speed this up. I myself would like to switch to Zed permanently and want to help in any way that might get this out sooner.

**Comment by indrajit-roy** [comment]
Can the community contribute to this? It would be nice to see the approach and design hosted somewhere so that interested folks can help speed up the process. I myself would like to switch to Zed permanently and am more than willing to help ship this asap. This is a huge and the only blocker for me right now.

**Comment by SomeoneToIgnore** [comment]
Of course it can, this is the whole point of Zed being open source.

I would suggest starting from something small-scoped, come up with the proposals and (ideally) some design drafts to discuss it first — defining the right chunk of work is the most complicated first step here, it seems.

Be wary that some subtasks of this "epic" are quite hard, e.g. the whole "show a two panel diff" story that will require writing something like https://github.com/zed-industries/zed/blob/main/crates/editor/src/display_map/inlay_map.rs but for git things.

**Comment by indrajit-roy** [comment]
> Of course it can, this is the whole point of Zed being open source.
> 
> I would suggest starting from something small-scoped, come up with the proposals and (ideally) some design drafts to discuss it first — defining the right chunk of work is the most complicated first step here, it seems.
> 

Of course. Just want the existing specs to be highlighted so that anyone taking this up doesn't re think anything that's already decided on.

**Comment by SomeoneToIgnore** [comment]
I suspect there's nothing well formed, covering the entire integration task, only a few ideas split between people (right now I work on something related to diffs, there are some design drafts, etc.).
See also notes in the  https://zed.dev/channel/git-5484 channel for a rough plan on how to move it forward.

So, any proposal could easily be better than the current state. I would not take too much of an effort to draw detailed designs, as @\iamnbutler might have better ideas, but otherwise anything is free to be picked up due to https://github.com/zed-industries/zed/issues/8665#issuecomment-2074561256

**Comment by mrnugget** [comment]
Anyone's free to help, sure, although I would caution against picking up one of the bigger items — git commit view, git status view, git diff view — since they require a lot of design and conceptual thinking up front on and the Zed team does have opinions on all of them, we just need to find the time to get to it.

**Comment by MarcARoberge** [comment]
May I suggest a small increment for the git view? With the help of the hunk feature recently merged, we could add a "filter" to only see in the project panel the files with the git-status changed. This way we could get a list of all files and if we want to see the diff, we could use the expand all hunks feature for now.

**Comment by ophilli** [comment]
It would be really nice to have a  "Right Click > Open in github.com" or similar for lines that have a clear git blame.

**Comment by mrnugget** [comment]
> It would be really nice to have a "Right Click > Open in github.com" or similar for lines that have a clear git blame.

@ophilli: You can already click on the commit sha here to open it on the code host:

![screenshot-2024-05-13-09 26 18@2x](https://github.com/zed-industries/zed/assets/1185253/f75cf05d-f018-450a-8fd0-b1bac2ce3b98)

But I also just opened this PR: https://github.com/zed-industries/zed/pull/11734

**Comment by kevinfaveri** [comment]
> May I suggest a small increment for the git diff view? With the help of the hunk feature recently merged, we could add a "filter" to only see in the project panel the files with the git-status changed. This way we could get a list of all files and if we want to see the diff, we could use the expand all hunks feature for now.

hey @mrnugget this seems a really low hanging fruit, allowing to filter files in files view by git status being modified. Is anything we can expedite quickly? Would really help with easily going to files that got modified in a "stable sidebar"

**Comment by SomeoneToIgnore** [comment]
@kevinfaveri 

I would argue about `really` easy, as the devil is in the ergonomics details.
The main line of questions to your proposal is: what to do with those filtered items in the project panel? Given most other tool experience, there should be click listeners, showing the diffs somewhere, how Zed is supposed to display this and how all those items are interacting with each other?

My current idea is to reuse current git hunk diffs (inline diffs) functionality, and show all changed places of a singleton buffer inside of a multi buffer (as for search results: we do not show the entire file with multiple matches inside, but rather show take excerpts around the matches and show those in a multi buffer), with the diff hunks expanded always (?).

As a first attempt, I will use a single multi buffer for all file entries, and get a project panel to show only the entries, related to excerpts of that large multi buffer — those will be all files that have some git changed metadata (modified/added/removed/conflict/etc.).
Project panel now only shows real files, but that might not be very ergonomic for large files with many changes, so some fake entries might be required.
And whatever the entries are, they still have to support previous project panel features, but for a companion multi buffer now:
* select a corresponding file when multi buffer's selection changes, also support a reveal action
* scroll to an excerpt when clicking a project panel entry (instead of opening the editor for the file as we only do now)
* directory expands/unexpands and fold/unfolds

Currently, I have a https://github.com/zed-industries/zed/compare/main...kb/buffer-panel branch that, while not related to the git diff explicitly, allows to have a companion "project panel" for any generic multi buffer, with the practical emphasis on the project search view.

Moreover, this is the first time in project panel's code history to add some filters on top of the current "all files in the project"-only approach, and besides all the above, it has to deal with performance implication — we can definitely do better than the branch does currently.

------------------

So, I think I'm getting there and the road is interesting and possible conceptually.
A good amount of work and wiring has to happen along the way though, so maybe I'm not over by the end of June but who knows.

**Comment by joaodlf** [comment]
I would recommend the Zed team (or anyone building software like this) to take a look at the way Jetbrains handles git integration. From basic functionality like commit/pull, to the amazing log interface, as well as the individual file history feature that fits into the git log UI. Even small things like being able to quickly open a file+line number in GitHub/Gitlab. Jetbrains has completely nailed their git integration, it's a fundamental aspect of my productivity and very hard to move away from.

**Comment by indrajit-roy-sc** [comment]
Completely agree with @joaodlf 

If Zed can nail JetBrains' level Git integration and at the same time keep the memory consumption close to what it is right now, it will be the hugest win in the world of IDEs.

**Comment by cole-abbeduto-particle** [comment]
Would love to see a list of remote branches to be able to easily select in the dropdown like Webstorm has 🙏

**Comment by szabba** [comment]
As a counterpoint: I personally avoid most git-related features in IntelliJ like the plague - with the exception of 3-way merge. The UI is complex and confusing, I recall operations having non-git names - I've learned git first, IntelliJ second, so that's beyond unhelpful. I've found that when I use VS Code I use the provided git integration much more readily.

**Comment by SomeoneToIgnore** [comment]
As a heads-up, the preparation phase for the project diff view is forming: https://github.com/zed-industries/zed/pull/12637

I plan to test it internally and release around Zed 0.141 , meanwhile iterating on top of this feature with more git-related changes: the new feature allows to show a multi buffer with all non-staged changes in the project, backed by the outline view.
If that prototype shows good signs, we can start a (somewhat) long road towards a proper project git diff view:
* add a way to show staged files similar to unstaged ones
* show conflicts properly
* potentially add more entries (not just outlines) below the changed files
* consider adding a commit input + pull/push buttons under the outline tree, similar to what Intellij has?
* somehow improve the egonomics around git diff hunks, maybe inlining them inside another GitMap inside the Editor.
* ... whatever else along the road

**Comment by Wragdan** [comment]
An interface similar to vim-fugitive could be cool. I'm trying to use zed as an alternative to neovim (testing it mostly).

**Comment by eddiebergman** [comment]
I'm also coming from Neovim for testing zed (very smooth so far!) and I second @Wragdan's suggestion of investigating fugitive's design. What I particularly like is that it really emulates 3 of the most common git commands you'll find across all levels of experience, `git status`, `git add` and `git commit`. It even looks very similar to `git status` in it's UI. However there's a huge amount of functionality hidden in the keymaps/_right-click_ that is not needed in 99% of usage.

Seconding @szabba's points, I've had to teach juniors about basic git things and somehow through jetbrains, it makes some very simple things drowned in several popup windows and non-labelled and confusing buttons. 

---

Just as a short illustration:

There's a simple stage and unstage on the right I can pop up, preview file hunks when _hovering_ over a file. Adding a file or hunk is straight forward by hitting `a` on either the file/hunk and when I'm ready, I can hit `,gc` and just write the commit message, collapsing the whole side bar and letting me get back to the main editor view. 

![Screenshot_2024-06-22_01-08-53](https://github.com/zed-industries/zed/assets/15933394/23b82c61-1452-48a4-b768-197a26244cde)

---

As a counterpoint to fugitive, it's aimed at keyboard centric users. It may not play well from a click-based perspective in design space.

**Comment by SomeoneToIgnore** [comment]
A small update on the project diff side: there's a prototype branch https://github.com/zed-industries/zed/compare/kb/project-diff?expand=1 which adds an action to create a multi buffer with all git changes Zed can detect now (modified files only, no staged changes) and maintains buffer's excerpts' order as in the project/outline panels with the FS tree.

https://github.com/zed-industries/zed/assets/2690773/41d7947e-b738-4d30-a868-975d6c333ead

As the video tries to show, it reacts on the external FS events and auto expands all new changes in the excerpts.
The diff display based on displaying the expanded git hunks which is inconvenient for browsing large modified hunks — to mitigate that, the multi buffer could be split into a new pane, the PR does not aim to add any side-by-side multi buffer diff view.

I do not think it's ready to be merged at the current state:

1. Zed does not notice "added" and "deleted" files at all, which looks quite confusing (there's also no information about staged changes and conflicts, but those are missing everywhere in Zed, while all other additions and deletions are shown)

This might be relatively tricky to add though, as would need to create "fake" deleted buffers and store them somewhere (in the same diff view, presumably) — but even this PR would not include this, there should be a plan on how to add these and what are the complexities related.

2. Overall, new multi buffer experience feels a bit below regular Zed multi buffers:
    * it is slow to appear for certain changes in certain projects — presumably, due to waiting for all changed buffers to open, but maybe there's more to fix. Also, the clone of the buffer, appearing during the split, should clone the previous state instead of re-collecting it (updates are harder to do this way and might be fine for now to keep doing separately on each split)
    * there are some small (?) bugs in the update code — it mostly works, but seem to sometimes skip the changes highlights too aggressively if those are on the edge of the excerpt; maybe some extra changes are displayed too? More refactoring and testing is needed on that front. Most of these issues appear due to excerpts being rather narrow — changes on the edges need excerpts to expand in order to show the entire change highlight, and either we should do that automatically or, at least, enlarge the default diff excerpts' size for now.
    * there's a certain level of flickering that happens periodically during edits, esp. on the very first one (but not on the 2nd or 3rd change, which is peculiar) — while some level of it is inevitable during the current way Zed renders the excerpts, syncing them after the rest of the editor is painted, but here it seems that some invalidation might be to blame too, as these do not flicker always — either the editor/element.rs code or the diff panel code needs a check, the latter has a few TODO related to invalidation.
    * the whole UI is not finished yet — diff multi buffer's tab shows something copy pasted from the diagnostics now, and, ideally, should have a notable button in the status bar (similar to diagnostics, something dynamic with +20/-100 diff stats). Outline panel better show something different than outlines.

----------------------

All this does not seem hard, but still require a significant amount of work and concentration which I do not have at the moment — so, I will pause with this change for now and use the bits of my spare time on improving the outline panel first.
Now, I have all code needed to prototype new items inside, not just the outlines, so the project diff panel will benefit from this work nonetheless.

On the grand scheme of things, side-by-side diffs for this part seem to be the hardest task and won't appear before singleton buffers' side-by-side diff is implemented first.
I have ideas on how to prototype this for singletons already, and it seems that the only complexity is the scrolling (and the scrollbar in general), so maybe that happens before the project diff is merged in its first form.

Meanwhile, if anybody is interested enough to pick this up and fix the issues aforementioned — welcome a lot.
I'm also curious to get some feedback, if the current state (modulo bugs and performance) is good enough for the start, I might consider merging it first without more git entities supported.

**Comment by Peiffap** [comment]
Linking here for visibility: https://github.com/zed-industries/zed/issues/13511.

**Comment by secondl1ght** [comment]
Ex-Atom user here waiting for full featured Git integration before I can officially make the switch to Zed. I know you guys can do it! :)

**Comment by ninjarogue** [comment]
> We could also have some form of Merge Editor like it is in Visual Studio Code or maybe something even better

This would give me the final incentive to switch from vscode/webstorm/neovim to zed.

**Comment by htor** [comment]
> As a counterpoint: I personally avoid most git-related features in IntelliJ like the plague - with the exception of 3-way merge. The UI is complex and confusing, I recall operations having non-git names - I've learned git first, IntelliJ second, so that's beyond unhelpful. I've found that when I use VS Code I use the provided git integration much more readily.

It can be confusing with different terminologies, but remember there are more version control systems than git so using generic names in the UI then makes sense.

**Comment by szabba** [comment]
I see how that's a reasonable thing to do if you want to paper over the differences between VCSes. I didn't get the impression that's a goal for zed (at least in this issue).

**Comment by ThatOneCalculator** [comment]
> Looking forward to this feature 🚀 For me it is a fundamental resource and with it I would be able to start a transition from vscode to zed ✨

It's being worked on, comments like these do nothing but flood notifications. A simple :+1: reaction does the job.

**Comment by 524c** [comment]
@ThatOneCalculator And it's inconsistent for you to comment to say that my comment is spam.

This is the same kind of reaction from radioactive people on StackOverflow.

I just wanted to show that I like the tool.

**Comment by NathanielH-snek** [comment]
> > Looking forward to this feature 🚀 For me it is a fundamental resource and with it I would be able to start a transition from vscode to zed ✨
> 
> It's being worked on, comments like these do nothing but flood notifications. A simple 👍 reaction does the job.

Ironically you too have flooded notifications. Also there is in fact no requirement to have notifications on, I’m sure when this issue is closed it’ll be very well documented in the release notes…

**Comment by ThatOneCalculator** [comment]
If you want to talk about spam... look at the sock puppet accounts coming in :smile: 

![image](https://github.com/user-attachments/assets/92bb300f-563a-4abb-b344-4c94aa9c4c67)

![image](https://github.com/user-attachments/assets/e3ebc5bf-cb8e-49d9-976d-40b320a8e2ee)

![image](https://github.com/user-attachments/assets/166c1220-49e4-4cd6-9a18-ddf03bed413b)

![image](https://github.com/user-attachments/assets/d82d5611-331a-4d87-b592-0283e23746d8)

**Comment by sha3072** [comment]
> Edit: "talk about" is meant entirely rhetorically. Let's get this conversation back on track.

I only made a positive comment.

You could just turn off notifications for this issue, but you'd rather just be nasty.

Who is flooding now? How ironic.

**Comment by 524c** [comment]
> If you want to talk about spam... look at the sock puppet accounts coming in 😄
> 
> ![image](https://private-user-images.githubusercontent.com/44733677/361279162-92bb300f-563a-4abb-b344-4c94aa9c4c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDEyMTIsIm5iZiI6MTcyNDY0MDkxMiwicGF0aCI6Ii80NDczMzY3Ny8zNjEyNzkxNjItOTJiYjMwMGYtNTYzYS00YWJiLWIzNDQtNGM5NGFhOWM0YzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAyNTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZDU0N2M4MjE1NzkxNTZiYzJiYTA3NjNkNzQ3NjBkYjJjYTg5MjAzMGEwOWRiZWM3NWNlMTg3M2IwZTU5ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J2MzcxRLVW-6euO6bbrDjpFG18-UgYp2pz7M0IYHQUU)
> 
> ![image](https://private-user-images.githubusercontent.com/44733677/361279216-e3ebc5bf-cb8e-49d9-976d-40b320a8e2ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDEyMTIsIm5iZiI6MTcyNDY0MDkxMiwicGF0aCI6Ii80NDczMzY3Ny8zNjEyNzkyMTYtZTNlYmM1YmYtY2I4ZS00OWQ5LTk3NmQtNDBiMzIwYThlMmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAyNTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4Y2MxZTg3NjU2NjA2NzUwMzk4YTg0N2UyNDdhODA3YmEyZTU2Mzc0Mjc3YmQ2OTE4NzhlNzZmZTk1YjJkZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hYyhDYCKxfX8IXWGkaEpl3QL3yCbnvZuBOLGYkJkdKE)
> 
> ![image](https://private-user-images.githubusercontent.com/44733677/361279259-166c1220-49e4-4cd6-9a18-ddf03bed413b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDEyMTIsIm5iZiI6MTcyNDY0MDkxMiwicGF0aCI6Ii80NDczMzY3Ny8zNjEyNzkyNTktMTY2YzEyMjAtNDllNC00Y2Q2LTlhMTgtZGRmMDNiZWQ0MTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAyNTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NzMwMTkxZjdiMDY2NWQ4MzZiOTg0MWRiZTEzNGYxNjg0MmZjZDFjMTVlM2Y1NDhkMjEyMjVmMTQ1YjcwOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lEWo8bMx17snhqQ0Pg4CAmcSnOSaB3RnlT3eHUD3Qdw)
> 
> ![image](https://private-user-images.githubusercontent.com/44733677/361279307-d82d5611-331a-4d87-b592-0283e23746d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDEyMTIsIm5iZiI6MTcyNDY0MDkxMiwicGF0aCI6Ii80NDczMzY3Ny8zNjEyNzkzMDctZDgyZDU2MTEtMzMxYS00ZDg3LWI1OTItMDI4M2UyMzc0NmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAyNTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5OTEwZjAwNjBlZTE2OTkwZmMxNDk3NmY4MTc5YWZkOWNjMmViYjgxMTQxMDJhMDJmYmNiMjA0Zjc5NjZhZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XOkXI3O8Dw1cvvZjASN1PC2CjK24GxuN-83t3HbJq2w)
> 
> Edit: "talk about" is meant entirely rhetorically. Let's get this conversation back on track.


Calm down Karen.

**Comment by 524c** [comment]
I made a respectful comment, just like others before and they marked it as spam.
<img width="948" alt="zed" src="https://github.com/user-attachments/assets/706ed889-1fef-4e60-8adc-1fe1f7c6e6dd">

I'm just another user showing their enthusiasm for the project.

A service or product must go beyond the technical.

Why did a notification bother this person so much? He could disable the notification, but he made a new comment to say that mine was a useless flood.

I don't know if it was the project owner who marked it as spam, it would be sad if it was.

**Comment by nxy7** [comment]
@524c I'm not contributor, but your comment was useless. Just add thumbs up and don't clutter discussions. 

I'm sure there are better places to show enthusiasm than comments that do not contribute anything to the issue. If you care about some software (like Zed) you should also try to make maintainers and contributors jobs easier - don't send comments that do not add anything to discussion, do not send notifications for no reason. After all it's in your best interest that development is as smooth as possible and you probably can imagine that some people need to follow tens of issues at once so such 'enthusiastic' comments add up and eat time that could otherwise be spent more productively.

**Comment by chrisdigital** [comment]
> > It would be really nice to have a "Right Click > Open in github.com" or similar for lines that have a clear git blame.
> 
> @ophilli: You can already click on the commit sha here to open it on the code host:
> 
> ![screenshot-2024-05-13-09 26 18@2x](https://private-user-images.githubusercontent.com/1185253/329960447-f75cf05d-f018-450a-8fd0-b1bac2ce3b98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNzIyODAsIm5iZiI6MTcyNjM3MTk4MCwicGF0aCI6Ii8xMTg1MjUzLzMyOTk2MDQ0Ny1mNzVjZjA1ZC1mMDE4LTQ1MGEtOGZkMC1iMWJhYzJjZTNiOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMDM0NjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM3ODIzZjljYjM5NTllMzI4MmUzZDIyZTA1OTJiOTk2YTcwOGZiNjc5MzhlMDU3OWU1YTA5OGIxMDgyZDQ2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bi_hWnUfd964efWl0rTn280OqlDRCfQlRyxrOhOxoao)
> 
> But I also just opened this PR: #11734

I this a current view one is supposed to be able to view? I don't see anything in the project view.

**Comment by mrnugget** [comment]
> Is this a current view one is supposed to be able to view?

You open it with `editor: toggle git blame`

**Comment by NiloCK** [comment]
Can `Stage Hunk` get added as a command in the command palate and in the context menu for a hunk?

![image](https://github.com/user-attachments/assets/ca434685-3d2b-4382-ae06-ee15b8f046dd)

Behavior similar to VSCode's `Stage Selected Ranges`

This will maybe be less popular, but I'd also *love* a `Stash Hunk` command in the same contexts.

Apologies if this is a dupe, but I didn't find it.

**Comment by mrnugget** [comment]
Milestone 1

**Comment by gavinmorrow** [comment]
Would it be possible to make the files in the tab bar also show if they are new/modified (the same way they are in the project files)? I keep finding myself looking for that.

**Comment by lionel-** [comment]
Ideas for committing while doing collab/pairing work:

- Option to automatically add `Co-author` lines to commit messages for people connected in the session.
- Allow all participants to commit. If they initiate a commit, they become "first author" and others get a `Co-author` mention.

**Comment by mrnugget** [comment]
Not sure what you're after, but we didn't tag all issues/PRs for this milestone. It was a manual process to check off the checkboxes here.

**Comment by baldwindavid** [comment]
For those that like TUIs, I use lazygit from within Zed and perhaps that can tide over some of those waiting for builtin functionality. 

The general idea is to set a keybinding that opens lazygit in a center terminal as another tab...

```json
  {
    "bindings": {
      "cmd-g": [
        "workspace::SendKeystrokes",
        ": new center terminal enter lazygit enter"
      ],
  },
```

![2024-10-29T183556@2x](https://github.com/user-attachments/assets/e5b76628-1e91-4f8f-972d-f716c48ac713)

I do use and enjoy the already builtin blame features in Zed, but not sure I'd stop using lazygit even if advanced builtin functionality were to exist. Maybe a fancy UI for tricky merge conflict resolution, but that would be way off in the future and I tend to crack open Sublime Merge for that anyway.

**Comment by reslear** [comment]
> Maybe a fancy UI for tricky merge conflict resolution, but that would be way off in the future and I tend to crack open Sublime Merge for that anyway.

![CleanShot 2024-11-06 at 17 55 01@2x](https://github.com/user-attachments/assets/ac638f9a-e558-4f0b-9d2b-34928429a2bc)

By the way, maybe someone knows how to implement the function 
“Open repository in Sublime Merge” as in https://github.com/giovdk21/vscode-sublime-merge ?

**Comment by andreacfromtheapp** [comment]
Dear Zed developers,

sorry to be adding to the list but I would immensely appreciate if Zed took a few hints from

- [lazygit](https://github.com/jesseduffield/lazygit)
- [magit](https://magit.vc/)

when addint this feature.

Please and thamk you

**Comment by lorenzodejong** [comment]
Specifically when having to perform merge conflicts i find myself switching back and forth between Zed and VS Code.

I'm using [lazygit](https://github.com/jesseduffield/lazygit) for basic status, diff and commit history. However i noticed a couple shortcomings when using this workflow for resolving merge conflicts compared to using VS Code's inline conflict resolution:
- In some cases it's desired to manually edit a merge conflict, specifically in scenarios where both the incoming and current branch contain relevant changes. In this case i usually "take both" and manually edit the change to the desired result. However this would require me to manually open the file after merging from lazygit, which is rather cumbersome.
- Missing IDE type-safety, after choosing a conflict resolution i'm used to immediately seeing potential type errors arise in my IDE. This is also missing from this workflow.

It would be amazing to have a UI within the Zed buffer to perform conflict resolution, as well as a git panel which displays files containing a merge conflict.

**Comment by idr4n** [comment]
As another alternative, in addition to LazyGit and Sublime Merge mentioned already, recently discovered Gitu (https://github.com/altsem/gitu), which is based on Magit but in the terminal, so it can be easily integrated in Zed as well.

**Comment by eugeneAtKnaufD** [comment]
> For those that like TUIs, I use [lazygit](https://github.com/jesseduffield/lazygit) from within Zed and perhaps that can tide over some of those waiting for builtin functionality.
> 
> The general idea is to set a keybinding that opens lazygit in a center terminal as another tab...
> 
>   {
>     "bindings": {
>       "cmd-g": [
>         "workspace::SendKeystrokes",
>         ": new center terminal enter lazygit enter"
>         
>         // Note: non-vim users would have to do something like below to open the command palette...
>         // "cmd-shift-p new center terminal enter lazygit enter"
>       ],
>   },
> ![2024-10-29T183556@2x](https://github.com/user-attachments/assets/e5b76628-1e91-4f8f-972d-f716c48ac713)
> 
> I do use and enjoy the already builtin blame features in Zed, but not sure I'd stop using lazygit even if advanced builtin functionality were to exist. Maybe a fancy UI for tricky merge conflict resolution, but that would be way off in the future and I tend to crack open Sublime Merge for that anyway.

For anyone wondering why this is no longer working, here is the workaround:
```jsonc
"bindings": {
    "cmd-g": ["task::Spawn", { "task_name": "Run Lazygit" }]
}

// and in tasks.json
{
    "label": "Run Lazygit",
    "command": "lazygit",
    "use_new_terminal": true,
    "reveal_target": "center"
}
```

**Comment by Gambloide** [comment]
> For anyone wondering why this is no longer working, here is the workaround:
> ``` javascript
> "bindings": {
>     "cmd-g": ["task::Spawn", { "task_name": "Run Lazygit" }]
> }
> 
> // and in tasks.json
> {
>     "label": "Run Lazygit",
>     "command": "lazygit",
>     "use_new_terminal": true,
>     "reveal_target": "center"
> }
> ```

After exiting lazygit with `q`, this approach leaves an unclosable tab with the following contents on Linux:

```
⏵ Task `Run Lazygit` finished successfully
⏵ Command: /bin/bash -i -c 'lazygit'
```

Neither clicking the `x` in the tab switcher closes it, nor any keyboard shortcuts like `ctrl-w`, `ctrl-d`, `ctrl-c`, etc.

I had to add `"hide": "on_success"` to the task to work around this issue with the workaround:

``` javascript
// in ~/.config/zed/tasks.json
[
    {
        "label": "Run Lazygit",
        "command": "lazygit",
        "use_new_terminal": true,
        "reveal_target": "center",
        "hide": "on_success"
    }
]
```

**Comment by JosephTLyons** [comment]
Hey everyone, just wanted to let you all know that we have opened a waitlist for our deeper git integration support [here](https://zed.dev/git?g=41). We will be rolling the beta out very soon.

**Comment by maxbrunsfeld** [comment]
This shipped.
