### ISSUE TITLE
Tracking Issue: Notebooks

### ISSUE THREAD

**Issue by rgbkrk** [zed-industries/zed#9778]
### Check for existing issues

- [X] Completed

## Problem

As evidenced in https://github.com/zed-industries/zed/issues/5273,  
Jupyter Notebook users would love to edit notebooks. There's a need for seamless integration that supports the variety of media types in Jupyter notebooks and the interactive runtimes underneath.

### File support

* [x] New filetype support (https://github.com/zed-industries/zed/pull/9353, https://github.com/zed-industries/zed/pull/9425)
* [ ] Load Jupyter notebooks `.ipynb` into a new viewer

### Runtime support

TBDE

### Rich Media -> GPUI needs

Some of the needs for the notebook will require GPUI work. Some will be able to reuse existing components as is (`div`, `img`, markdown preview).

These are the [likely mediatypes to support](https://github.com/runtimed/runtimed/blob/main/runtimelib/src/media.rs#L9):

* [x] `text/plain` -> `div()`
* [ ] `text/html` - no support, yet highly needed
- [x] `text/markdown` - presumed able to support based on markdown preview

- [ ] `text/latex` - For rendering mathematical expressions.
- [ ] `application/javascript` - no support

- [x] `application/json` - likely to be made with a custom component or a read-only buffer
- [x] Image formats (`image/svg+xml`, `image/png`, `image/jpeg`, `image/gif`)
- [ ] `application/vnd.jupyter.widget-view+json`, `application/vnd.jupyter.widget-state+json` - no support
- [ ] Geospatial data (`application/geo+json`)
- [ ]  VegaLite, Vega - unknown ability to support
- [ ] `application/vnd.dataresource+json` - develop a custom table component to elegantly display tabular data within notebooks without needing `text/html` media type

### Rich Media rendering

Same list as above, with actual implementation

* [ ] `text/plain`
* [ ] `text/html`
- [ ] `text/markdown`
- [ ] `text/latex`
- [ ] `application/javascript`
- [ ] `application/json`
- [ ] Image formats (`image/svg+xml`, `image/png`, `image/jpeg`, `image/gif`)
- [ ] `application/vnd.jupyter.widget-view+json`, `application/vnd.jupyter.widget-state+json` - no support
- [ ] `application/geo+json`
- [ ]  VegaLite, Vega
- [ ] `application/vnd.dataresource+json`

**Comment by jianghoy** [comment]
Regarding `text/latex`, I believe today's best option is: `MathJax`(the default Tex implementation in webstack) -> `Rust binding of MathJax running on node`(the biggest unknown, talk about it below) -> `SVG` (which is supported by GPUI). Given Zed has a very low level UI support it should be reasonable to implement a mix of text, md, and SVG layout.

# MathJax binding
Today there's a rust crate called [MathJax](https://docs.rs/mathjax/latest/mathjax/), however, the level of support is questionable. And I feel using a headless chrome as nodejs backend for Mathjax is a big yellow flag.  
There's also a [KaTex rust binding](https://docs.rs/katex/latest/katex/), which uses [quickjs](https://bellard.org/quickjs/)(a small and fast and almost feature complete js engine implementation by Fabrice Bellard) or wasm js as node backend. But I don't think KaTex supports outputting to SVG (correct me if I'm wrong).  
Hence, the best option forward I believe would be:
1. either raise a PR to the current MathJax rust repo and add quickjs as a backend; or create a new crate that does it;
2. also, it would be wise to setup CICD that automatically updates MathJax version in the rust binding; one concern I have over these 3rd party wrapper is that, when upstream releases a patch, downstream may not be responsive even though the change will be minimal. And CICD could help that.

**Comment by vultix** [comment]
What’s the plan for supporting html rendering? This is an important feature for Jupyter, and I can think of a few other use cases for wanting an embedded browser / web renderer in Zed

**Comment by rgbkrk** [comment]
My first pass is going to involve using table schema instead of HTML for the most important use case: viewing data frames. Long term HTML support in GPUI is a big unknown to me.

**Comment by vultix** [comment]
@rgbkrk I have a working proof of concept of embedding a [wry](https://github.com/tauri-apps/wry) webview into GPUI. It's surprisingly simple, and surprisingly performant even with ~100 small webviews in a GPUI scrolling div.

First, add wry as a dependency in your Cargo.toml:
```toml
wry = "0.39.0"
```

Then, add this to the `impl WindowContext` in `crates/gpui/src/window.rs`
```rust
    /// Returns a reference to window's raw_window_handle::HasWindowHandle type
    pub fn raw_window_handle(&self) -> &dyn HasWindowHandle {
        &self.window.platform_window
    }

```

Finally, here's how I made a simple webview. Very kludgy, but works as a proof of concept:
```rust
use std::sync::Arc;

use gpui::*;
use wry::{dpi, Rect, WebView};
use wry::dpi::LogicalSize;
use wry::raw_window_handle::HasWindowHandle;

struct WebViewTest {
    views: Vec<Arc<WebView>>,
}

impl WebViewTest {
    fn new(num_views: usize, handle: &dyn HasWindowHandle) -> Self {
        let views = (0..num_views)
            .map(|i| {
                Arc::new(
                    wry::WebViewBuilder::new_as_child(&handle)
                        .with_html(format!(
                            "<html><body>Hello, world! I'm webview {i}</body></html>"
                        ))
                        .build()
                        .unwrap(),
                )
            })
            .collect();

        Self { views }
    }
}

impl Render for WebViewTest {
    fn render(&mut self, cx: &mut ViewContext<Self>) -> impl IntoElement {
        let mut parent = div()
            .id("parent")
            .block()
            .overflow_y_scroll()
            .size_full()
            .bg(rgb(0xff0000))
            .justify_center()
            .items_center();

        for (i, view) in self.views.iter().enumerate() {
            parent = parent.child(
                div()
                    .size(Length::Definite(DefiniteLength::Absolute(
                        AbsoluteLength::Pixels(Pixels(100.0)),
                    )))
                    .bg(rgb(0x00ff00))
                    .child(format!("This is webview {}:", i)),
            );
            parent = parent.child(HelloWorldEl { view: view.clone() });
        }

        parent
    }
}

struct HelloWorldEl {
    view: Arc<WebView>,
}
impl IntoElement for HelloWorldEl {
    type Element = HelloWorldEl;

    fn into_element(self) -> Self::Element {
        self
    }
}

impl Element for HelloWorldEl {
    type BeforeLayout = ();
    type AfterLayout = ();

    fn before_layout(&mut self, cx: &mut ElementContext) -> (LayoutId, Self::BeforeLayout) {
        let mut style = Style::default();
        style.flex_grow = 1.0;
        style.size = Size::full();
        let id = cx.request_layout(&style, []);
        (id, ())
    }

    fn after_layout(
        &mut self,
        bounds: Bounds<Pixels>,
        before_layout: &mut Self::BeforeLayout,
        cx: &mut ElementContext,
    ) -> Self::AfterLayout {
        // TODO: Find better way of detecting view visibility
        if bounds.top() > cx.viewport_size().height || bounds.bottom() < Pixels::ZERO {
            self.view.set_visible(false).unwrap();
        } else {
            self.view.set_visible(true).unwrap();

            self.view
                .set_bounds(Rect {
                    size: dpi::Size::Logical(LogicalSize {
                        width: (bounds.size.width.0 - 50.0).into(),
                        height: (bounds.size.height.0 / 2.0).into(),
                    }),
                    position: dpi::Position::Logical(dpi::LogicalPosition::new(
                        bounds.origin.x.into(),
                        bounds.origin.y.into(),
                    )),
                })
                .unwrap();
        }
    }

    fn paint(
        &mut self,
        bounds: Bounds<Pixels>,
        before_layout: &mut Self::BeforeLayout,
        after_layout: &mut Self::AfterLayout,
        cx: &mut ElementContext,
    ) {
        // Do nothing?
    }
}

fn main() {
    App::new().run(|cx: &mut AppContext| {
        let bounds = Bounds::centered(None, size(px(600.0), px(600.0)), cx);
        cx.open_window(
            WindowOptions {
                bounds: Some(bounds),
                ..Default::default()
            },
            |cx| {
                cx.activate_window();

                let view = WebViewTest::new(50, cx.raw_window_handle());
                cx.new_view(|_cx| view)
            },
        );
    });
}
```

**Comment by isaacmclellan** [comment]
> @rgbkrk I have a working proof of concept of embedding a [wry](https://github.com/tauri-apps/wry) webview into GPUI. It's surprisingly simple, and surprisingly performant even with ~100 small webviews in a GPUI scrolling div.
> 
> First, add wry as a dependency in your Cargo.toml:
> 
> ```toml
> wry = "0.39.0"
> ```
> 
> Then, add this to the `impl WindowContext` in `crates/gpui/src/window.rs`
> 
> ```rust
>     /// Returns a reference to window's raw_window_handle::HasWindowHandle type
>     pub fn raw_window_handle(&self) -> &dyn HasWindowHandle {
>         &self.window.platform_window
>     }
> ```
> 
> Finally, here's how I made a simple webview. Very kludgy, but works as a proof of concept:
> 
> ```rust
> use std::sync::Arc;
> 
> use gpui::*;
> use wry::{dpi, Rect, WebView};
> use wry::dpi::LogicalSize;
> use wry::raw_window_handle::HasWindowHandle;
> 
> struct WebViewTest {
>     views: Vec<Arc<WebView>>,
> }
> 
> impl WebViewTest {
>     fn new(num_views: usize, handle: &dyn HasWindowHandle) -> Self {
>         let views = (0..num_views)
>             .map(|i| {
>                 Arc::new(
>                     wry::WebViewBuilder::new_as_child(&handle)
>                         .with_html(format!(
>                             "<html><body>Hello, world! I'm webview {i}</body></html>"
>                         ))
>                         .build()
>                         .unwrap(),
>                 )
>             })
>             .collect();
> 
>         Self { views }
>     }
> }
> 
> impl Render for WebViewTest {
>     fn render(&mut self, cx: &mut ViewContext<Self>) -> impl IntoElement {
>         let mut parent = div()
>             .id("parent")
>             .block()
>             .overflow_y_scroll()
>             .size_full()
>             .bg(rgb(0xff0000))
>             .justify_center()
>             .items_center();
> 
>         for (i, view) in self.views.iter().enumerate() {
>             parent = parent.child(
>                 div()
>                     .size(Length::Definite(DefiniteLength::Absolute(
>                         AbsoluteLength::Pixels(Pixels(100.0)),
>                     )))
>                     .bg(rgb(0x00ff00))
>                     .child(format!("This is webview {}:", i)),
>             );
>             parent = parent.child(HelloWorldEl { view: view.clone() });
>         }
> 
>         parent
>     }
> }
> 
> struct HelloWorldEl {
>     view: Arc<WebView>,
> }
> impl IntoElement for HelloWorldEl {
>     type Element = HelloWorldEl;
> 
>     fn into_element(self) -> Self::Element {
>         self
>     }
> }
> 
> impl Element for HelloWorldEl {
>     type BeforeLayout = ();
>     type AfterLayout = ();
> 
>     fn before_layout(&mut self, cx: &mut ElementContext) -> (LayoutId, Self::BeforeLayout) {
>         let mut style = Style::default();
>         style.flex_grow = 1.0;
>         style.size = Size::full();
>         let id = cx.request_layout(&style, []);
>         (id, ())
>     }
> 
>     fn after_layout(
>         &mut self,
>         bounds: Bounds<Pixels>,
>         before_layout: &mut Self::BeforeLayout,
>         cx: &mut ElementContext,
>     ) -> Self::AfterLayout {
>         // TODO: Find better way of detecting view visibility
>         if bounds.top() > cx.viewport_size().height || bounds.bottom() < Pixels::ZERO {
>             self.view.set_visible(false).unwrap();
>         } else {
>             self.view.set_visible(true).unwrap();
> 
>             self.view
>                 .set_bounds(Rect {
>                     size: dpi::Size::Logical(LogicalSize {
>                         width: (bounds.size.width.0 - 50.0).into(),
>                         height: (bounds.size.height.0 / 2.0).into(),
>                     }),
>                     position: dpi::Position::Logical(dpi::LogicalPosition::new(
>                         bounds.origin.x.into(),
>                         bounds.origin.y.into(),
>                     )),
>                 })
>                 .unwrap();
>         }
>     }
> 
>     fn paint(
>         &mut self,
>         bounds: Bounds<Pixels>,
>         before_layout: &mut Self::BeforeLayout,
>         after_layout: &mut Self::AfterLayout,
>         cx: &mut ElementContext,
>     ) {
>         // Do nothing?
>     }
> }
> 
> fn main() {
>     App::new().run(|cx: &mut AppContext| {
>         let bounds = Bounds::centered(None, size(px(600.0), px(600.0)), cx);
>         cx.open_window(
>             WindowOptions {
>                 bounds: Some(bounds),
>                 ..Default::default()
>             },
>             |cx| {
>                 cx.activate_window();
> 
>                 let view = WebViewTest::new(50, cx.raw_window_handle());
>                 cx.new_view(|_cx| view)
>             },
>         );
>     });
> }
> ```

nothing to do with the original issue, but this doesn't work on the latest version of GPUI how can do you get it to work?

**Comment by isaacmclellan** [comment]
> > @rgbkrk I have a working proof of concept of embedding a [wry](https://github.com/tauri-apps/wry) webview into GPUI. It's surprisingly simple, and surprisingly performant even with ~100 small webviews in a GPUI scrolling div.
> > First, add wry as a dependency in your Cargo.toml:
> > ```toml
> > wry = "0.39.0"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then, add this to the `impl WindowContext` in `crates/gpui/src/window.rs`
> > ```rust
> >     /// Returns a reference to window's raw_window_handle::HasWindowHandle type
> >     pub fn raw_window_handle(&self) -> &dyn HasWindowHandle {
> >         &self.window.platform_window
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Finally, here's how I made a simple webview. Very kludgy, but works as a proof of concept:
> > ```rust
> > use std::sync::Arc;
> > 
> > use gpui::*;
> > use wry::{dpi, Rect, WebView};
> > use wry::dpi::LogicalSize;
> > use wry::raw_window_handle::HasWindowHandle;
> > 
> > struct WebViewTest {
> >     views: Vec<Arc<WebView>>,
> > }
> > 
> > impl WebViewTest {
> >     fn new(num_views: usize, handle: &dyn HasWindowHandle) -> Self {
> >         let views = (0..num_views)
> >             .map(|i| {
> >                 Arc::new(
> >                     wry::WebViewBuilder::new_as_child(&handle)
> >                         .with_html(format!(
> >                             "<html><body>Hello, world! I'm webview {i}</body></html>"
> >                         ))
> >                         .build()
> >                         .unwrap(),
> >                 )
> >             })
> >             .collect();
> > 
> >         Self { views }
> >     }
> > }
> > 
> > impl Render for WebViewTest {
> >     fn render(&mut self, cx: &mut ViewContext<Self>) -> impl IntoElement {
> >         let mut parent = div()
> >             .id("parent")
> >             .block()
> >             .overflow_y_scroll()
> >             .size_full()
> >             .bg(rgb(0xff0000))
> >             .justify_center()
> >             .items_center();
> > 
> >         for (i, view) in self.views.iter().enumerate() {
> >             parent = parent.child(
> >                 div()
> >                     .size(Length::Definite(DefiniteLength::Absolute(
> >                         AbsoluteLength::Pixels(Pixels(100.0)),
> >                     )))
> >                     .bg(rgb(0x00ff00))
> >                     .child(format!("This is webview {}:", i)),
> >             );
> >             parent = parent.child(HelloWorldEl { view: view.clone() });
> >         }
> > 
> >         parent
> >     }
> > }
> > 
> > struct HelloWorldEl {
> >     view: Arc<WebView>,
> > }
> > impl IntoElement for HelloWorldEl {
> >     type Element = HelloWorldEl;
> > 
> >     fn into_element(self) -> Self::Element {
> >         self
> >     }
> > }
> > 
> > impl Element for HelloWorldEl {
> >     type BeforeLayout = ();
> >     type AfterLayout = ();
> > 
> >     fn before_layout(&mut self, cx: &mut ElementContext) -> (LayoutId, Self::BeforeLayout) {
> >         let mut style = Style::default();
> >         style.flex_grow = 1.0;
> >         style.size = Size::full();
> >         let id = cx.request_layout(&style, []);
> >         (id, ())
> >     }
> > 
> >     fn after_layout(
> >         &mut self,
> >         bounds: Bounds<Pixels>,
> >         before_layout: &mut Self::BeforeLayout,
> >         cx: &mut ElementContext,
> >     ) -> Self::AfterLayout {
> >         // TODO: Find better way of detecting view visibility
> >         if bounds.top() > cx.viewport_size().height || bounds.bottom() < Pixels::ZERO {
> >             self.view.set_visible(false).unwrap();
> >         } else {
> >             self.view.set_visible(true).unwrap();
> > 
> >             self.view
> >                 .set_bounds(Rect {
> >                     size: dpi::Size::Logical(LogicalSize {
> >                         width: (bounds.size.width.0 - 50.0).into(),
> >                         height: (bounds.size.height.0 / 2.0).into(),
> >                     }),
> >                     position: dpi::Position::Logical(dpi::LogicalPosition::new(
> >                         bounds.origin.x.into(),
> >                         bounds.origin.y.into(),
> >                     )),
> >                 })
> >                 .unwrap();
> >         }
> >     }
> > 
> >     fn paint(
> >         &mut self,
> >         bounds: Bounds<Pixels>,
> >         before_layout: &mut Self::BeforeLayout,
> >         after_layout: &mut Self::AfterLayout,
> >         cx: &mut ElementContext,
> >     ) {
> >         // Do nothing?
> >     }
> > }
> > 
> > fn main() {
> >     App::new().run(|cx: &mut AppContext| {
> >         let bounds = Bounds::centered(None, size(px(600.0), px(600.0)), cx);
> >         cx.open_window(
> >             WindowOptions {
> >                 bounds: Some(bounds),
> >                 ..Default::default()
> >             },
> >             |cx| {
> >                 cx.activate_window();
> > 
> >                 let view = WebViewTest::new(50, cx.raw_window_handle());
> >                 cx.new_view(|_cx| view)
> >             },
> >         );
> >     });
> > }
> > ```
> 
> nothing to do with the original issue, but this doesn't work on the latest version of GPUI what can do you get it to work?

@vultix

**Comment by NathanielH-snek** [comment]
> Wondering if anyone has any experience with [marimo](https://marimo.io) ([GitHub repo](https://github.com/marimo-team/marimo))? It looks really nice, with some benefits over Jupyter as discussed [here](https://marimo.io/blog/lessons-learned).

I'm also curious about this as well over jupyter notebooks, not having a whole different filetype in my workflows would be nice. Perhaps this could be an extension eventually?

**Comment by antaz** [comment]
I would like point out that it would be a good idea to make the REPL output scrollable, in the case of arbitrary long outputs, or truncate it somehow (Not sure what's the best solution)

![image](https://github.com/user-attachments/assets/8dd4aba5-e28f-4c25-b2a5-2cd91398fa52)

**Comment by NyanHelsing** [comment]
@vultix I've started a draft PR based on your comment here, and it looks like the methods on Element that gpui is expecting has changed. I' trying to update the implementation to match that, but any pointers you can throw my way are appreciated!! See https://github.com/zed-industries/zed/pull/17004/files

**Comment by majidaldo** [comment]
> Wondering if anyone has any experience with [marimo](https://marimo.io) ([GitHub repo](https://github.com/marimo-team/marimo))? It looks really nice, with some benefits over Jupyter as discussed [here](https://marimo.io/blog/lessons-learned).

If zed is looking to the future, it should just drop jupyter. It had its time. Zed could somehow 'embed' marimo.

**Comment by RicardStark** [comment]
@majidaldo I come from the STEM world, and I haven't heard one person mention Marimo. I've seen its Github, and while a lot of its default behaviors seem nice in comparison to the Jupyter defaults, one thing I see missing is one of the main gimmicks of with Jupyter, multiple language kernels. Do correct me if I am wrong, but I see no ability to run anything other than Python, which entirely ignores the fact that Jupyter literally stands for including Julia, Python, and R. That doesn't include the myriad of other languages that now have a language kernels that now support Jupyter.

I definitely agree its something to work on, but in terms of priority, strong communities and workflows around Jupyter already exist. I have my doubts I could say the same around marimo, though it definitely seems to be growing.

Do correct me if I have the wrong impression around community sizes.

**Comment by majidaldo** [comment]
> [@majidaldo](https://github.com/majidaldo) I come from the STEM world, and I haven't heard one person mention Marimo. I've seen its Github, and while a lot of its default behaviors seem nice in comparison to the Jupyter defaults, one thing I see missing is one of the main gimmicks of with Jupyter, multiple language kernels. Do correct me if I am wrong, but I see no ability to run anything other than Python, which entirely ignores the fact that Jupyter literally stands for including Julia, Python, and R. That doesn't include the myriad of other languages that now have a language kernels that now support Jupyter.
> 
> I definitely agree its something to work on, but in terms of priority, strong communities and workflows around Jupyter already exist. I have my doubts I could say the same around marimo, though it definitely seems to be growing.
> 
> Do correct me if I have the wrong impression around community sizes.

Of course if you have a decade+ head start that's going to happen.  The reactive computing model and state tracking of marimo is a better fit for zed users. Yes jupyter is multilingual but zed could just adopt the reactive computing tool of each language. I recall julia has one (why was one made if jupyter was good?)

For development and exploration, provided you stick to python, marimo is objectively superior. Python is a good 'meta interpreter' anyways that would allow you to work with multiple languages at the same time (jupyter can't).

**Comment by NathanielH-snek** [comment]
Marimo likely would be a good option as an extension, ideally using the native notebook ui. I've been learning rust and would love to try to get something like that working when I have a bit more time. Need to look more into how Marino works.

**Comment by jovezhong** [comment]
+1 for a marimo extension in zed. To me, marimo=notebook+streamlit, not sure how those interactive widgets will be rendered in zed editor

**Comment by JonGretar** [comment]
> +1 for a marimo extension in zed. To me, marimo=notebook+streamlit, not sure how those interactive widgets will be rendered in zed editor

I doubt they would as I think marimo does support it. Even the official VSCode plugin for marimo can not do it. In fact you can do almost everything the vscode plugin does in Zed currently with only snippets and tasks.

**Comment by JonGretar** [comment]
> What doesn't marimo support?
> 
> Also it sounds like you are saying Zed is able to do almost everything the marimo vscode plugin does already. Please explain.

Exporting output of cells as jupyter does. The VS code plugin just starts the web server and loads that in a embedded HTML browser. An effect you can achieve with a split screen with the browser. 

The only thing I can think of that VSCode can do that is the experimental notebook view of the source code. But that seems of limited usability and feels juryrigged and broken.

If you add these tasks and then insert the following snippets you have 80% of the thing VSCode does. I then like to set the marimo browser to automatically run stale cells.

```JSON
[
  {
    "label": "Run Marimo file",
    "command": "marimo run --watch  '$ZED_FILE'",
    "reveal": "always",
    "hide": "on_success"
  },
  {
    "label": "Edit Marimo file",
    "command": "marimo edit --watch  '$ZED_FILE'",
    "reveal": "always",
    "hide": "on_success"
  }
]
``` 

```JSON
{
  "Marimo App Cell": {
    "prefix": "mac",
    "description": "Create a Marimo app cell",
    "body": [
    "@app.cell",
    "def _(${1:mo}):",
    "    $0",
    "    return"
    ]
  },
  "Marimo MD": {
    "prefix": "mmd",
    "description": "Create a Marimo Markdown cell",
    "body": [
    "@app.cell",
    "def _(${1:mo}):",
    "    mo.md($2\"\"\"",
    "    $0",
    "    \"\"\")",
    "    return"
    ]
  },
}
```

**Comment by JonGretar** [comment]
> Sadly, notebook support has now been bumped off of the [Zed 1.0 (Fall 2025) roadmap](https://zed.dev/roadmap) to the "Beyond Zed 1.0" list. Looks like it won't be a priority for the foreseeable future.

Quite understandable really. But hopefully there will be some REPL improvements nevertheless. I would much rather see those than jupyter myself.

**Comment by jasongrout** [comment]
There is a lot of discussion of marimo and reactive computing in the comments above. Another option for reactive computing would be integration with [ipyflow](https://github.com/ipyflow/ipyflow), which provides a kernel with reactive execution. ipyflow currently has tight integration with Jupyter web frontends, but it [provides api tools](https://github.com/ipyflow/ipyflow?tab=readme-ov-file#colab-vscode-and-other-interfaces) that could be usable in other frontends even if they didn't have full ui support for reactive execution. CC @smacke

**Comment by smacke** [comment]
From my experience, it's quite hard to build a reactive notebook without deep control over / integration with the UI -- not to mention a successful reactive notebook like pluto, marimo, or observable. I think if zed were to implement something like reactivity, there wouldn't be a clear advantage to tying it to a particular implementation -- it could probably implement its own dependency parser-based reactive implementation with tree sitter for different languages, and enjoy deep integration with its editor. I'd love to see the community settle on a set of standards for reactivity but it seems like we're very far away from that.

Thinking about implementation effort for the execution engine / repl specifically -- jupyter is probably a bit easier to build on top of given the existence of an existing open protocol and multiple examples of clients that use that protocol (including a the `jupyter_client` library).

**Comment by passchaos** [comment]
> Sadly, notebook support has now been bumped off of the [Zed 1.0 (Fall 2025) roadmap](https://zed.dev/roadmap) to the "Beyond Zed 1.0" list. Looks like it won't be a priority for the foreseeable future.

Good news! I saw that the Notebook has returned to the 1.0 roadmap again

**Comment by diegoleteliers10** [comment]
@passchaos i saw that. Great news... hope they have it asap.

**Comment by lrisguan** [comment]
> Regarding `text/latex`, I believe today's best option is: `MathJax`(the default Tex implementation in webstack) -> `Rust binding of MathJax running on node`(the biggest unknown, talk about it below) -> `SVG` (which is supported by GPUI). Given Zed has a very low level UI support it should be reasonable to implement a mix of text, md, and SVG layout.
> 
> # MathJax binding
> Today there's a rust crate called [MathJax](https://docs.rs/mathjax/latest/mathjax/), however, the level of support is questionable. And I feel using a headless chrome as nodejs backend for Mathjax is a big yellow flag. There's also a [KaTex rust binding](https://docs.rs/katex/latest/katex/), which uses [quickjs](https://bellard.org/quickjs/)(a small and fast and almost feature complete js engine implementation by Fabrice Bellard) or wasm js as node backend. But I don't think KaTex supports outputting to SVG (correct me if I'm wrong). Hence, the best option forward I believe would be:
> 
> 1. either raise a PR to the current MathJax rust repo and add quickjs as a backend; or create a new crate that does it;
> 2. also, it would be wise to setup CICD that automatically updates MathJax version in the rust binding; one concern I have over these 3rd party wrapper is that, when upstream releases a patch, downstream may not be responsive even though the change will be minimal. And CICD could help that.
> 
> Once these are sorted out, one can start verifying the work by adding Tex parsing into markdown similar to Jupyter and see if it renders correctly. This verification may or may not ship.

Hello, have you considered RaTeX (https://github.com/erweixin/RaTeX) as an alternative? It’s a KaTeX-compatible math renderer written in pure Rust — no JavaScript, no WebView, no DOM, no headless Chrome or Node backend needed.

Key advantages for Zed/GPUI:
- Pure Rust core with predictable memory (no GC), which fits Zed’s architecture well.
- Outputs directly to SVG, PNG, PDF, or a display list — SVG is already supported by GPUI.
- Cross-platform by design (iOS, Android, Flutter, Web, server-side), so it could cover all Zed targets.
- No upstream JS wrapper maintenance concerns; it’s self-contained.

Caveats to validate:
- Syntax coverage is ~99.5% of KaTeX (not 100%), so edge-case Jupyter formulas might need testing.
- It’s a relatively new project compared to MathJax/KaTeX, so long-term maintenance and community adoption are still to be proven.

**Comment by MostlyKIGuess** [comment]
Yeah, I was actually looking into RaTeX as well. I am sorry I haven't gotten some time but I was in talks with the Zed team around this and they did decide to re-open the math PR https://github.com/zed-industries/zed/pull/54668. I will see what makes a smaller binary b/w RaTeX and ReX

**Comment by lrisguan** [comment]
> Yeah, I was actually looking into RaTeX as well. I am sorry I haven't gotten some time but I was in talks with the Zed team around this and they did decide to re-open the math PR [#54668](https://github.com/zed-industries/zed/pull/54668). I will see what makes a smaller binary b/w RaTeX and ReX

Great! Appreciate your work — hope it goes well!

**Comment by Pioneer-1-1** [comment]
Any idea when we will see LSP within notebooks? The current version works pretty well in my experience but the lack of LSP inside the notebook kills it's ability to be used for any real work
